language: python

python:
 - "3.6"

install:
 - pip install -r requirements.txt

script:
 - python app_run.py


deploy:
 provider: heroku

 api_key: 
    secure: 7b4b9bd7-3510-4111-ad4c-904075ffe866

 app: heroku-test-lab4

 on:
    repo: bbbbbb123/SE

 run: "web: gunicorn app_run:app"